name: test
on: pull_request

permissions:
  pull-requests: write

jobs:
  dependabot:
    environment: npm-update
    # 22.04's podman has issues with piping and causes tar errors
    runs-on: ubuntu-20.04
    if: ${{ github.actor == 'jelly' }}
    steps:
      - name: test
        run: |
          echo '${{ secrets.NODE_CACHE_DEPLOY_KEY }}'
